version: "3"

services:
  home:
    container_name: home
    build:
      context: .
      dockerfile: ./apps/home/Dockerfile
    ports:
      - 3001:3001
  shop:
    container_name: shop
    build:
      context: .
      dockerfile: ./apps/shop/Dockerfile
    ports:
      - 3002:3002
  checkout:
    container_name: checkout
    build:
      context: .
      dockerfile: ./apps/checkout/Dockerfile
    ports:
      - 3000:3000

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   app_network:
#     external: true